In [2]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
reshaped_arr=arr.reshape(2,5)
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
addition=sum(A,B)
multiplication=A*B
print("addition of two matrices is",addition)
print("multipication of two matrices is",multiplication)

addition of two matrices is [[ 9 12]
 [11 14]]
multipication of two matrices is [[ 5 12]
 [21 32]]


In [19]:
dot_prdt=np.dot(addition,multiplication)
trans=np.transpose(dot_prdt)
print("the dot product two matrices is", dot_prdt)
print("the transpose is", trans) 

the dot product two matrices is [[297 492]
 [349 580]]
the transpose is [[297 349]
 [492 580]]


In [22]:
my_array=np.array([5,15,7,35,10])
my_array[my_array<10]=0
print(my_array)

[ 0 15  0 35 10]


In [24]:
reversed_array=np.flip(my_array)
print(reversed_array)

[10 35  0 15  0]


In [4]:
mean=np.mean(my_array)
median=np.median(my_array)
std_dev=np.std(my_array)
print("mean is",mean)
print("median is",median)
print("standard deviattion is",std_dev)

mean is 3.0
median is 3.0
standard deviattion is 1.4142135623730951


In [5]:
import numpy as np
my_array=np.array([1,2,3,4,5])
np.save('array_file.npy',my_array)
loaded_array=np.load('array_file.npy')
print("loaded array:",loaded_array)

loaded array: [1 2 3 4 5]


In [7]:
my_arr=np.array([[1,2,3],[4,5,6]])
np.savetxt('array_data.csv',my_arr)
loaded_arr=np.loadtxt('array_data.csv')
print("loaded array is",loaded_arr)

loaded array is [[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
merged_array=np.hstack((a,b))
print("horizontally merged array:",merged_array)

horizontally merged array: [[1 2 5 6]
 [3 4 7 8]]
